// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipc.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ipc {

  /// <summary>Holder for reflection information generated from ipc.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class IpcReflection {

    #region Descriptor
    /// <summary>File descriptor for ipc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IpcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglpcGMucHJvdG8SA2lwYyIgChBLZWVwQWxpdmVSZXF1ZXN0EgwKBHRlc3QY",
            "ASABKAkiIQoRS2VlcEFsaXZlUmVzcG9uc2USDAoEdGVzdBgBIAEoCTJGCgZN",
            "YXN0ZXISPAoJS2VlcEFsaXZlEhUuaXBjLktlZXBBbGl2ZVJlcXVlc3QaFi5p",
            "cGMuS2VlcEFsaXZlUmVzcG9uc2UiADIHCgVTbGF2ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.KeepAliveRequest), global::Ipc.KeepAliveRequest.Parser, new[]{ "Test" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ipc.KeepAliveResponse), global::Ipc.KeepAliveResponse.Parser, new[]{ "Test" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class KeepAliveRequest : pb::IMessage<KeepAliveRequest> {
    private static readonly pb::MessageParser<KeepAliveRequest> _parser = new pb::MessageParser<KeepAliveRequest>(() => new KeepAliveRequest());
    public static pb::MessageParser<KeepAliveRequest> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.IpcReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public KeepAliveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    public KeepAliveRequest(KeepAliveRequest other) : this() {
      test_ = other.test_;
    }

    public KeepAliveRequest Clone() {
      return new KeepAliveRequest(this);
    }

    /// <summary>Field number for the "test" field.</summary>
    public const int TestFieldNumber = 1;
    private string test_ = "";
    public string Test {
      get { return test_; }
      set {
        test_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as KeepAliveRequest);
    }

    public bool Equals(KeepAliveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Test != other.Test) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Test.Length != 0) hash ^= Test.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Test.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Test);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Test.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Test);
      }
      return size;
    }

    public void MergeFrom(KeepAliveRequest other) {
      if (other == null) {
        return;
      }
      if (other.Test.Length != 0) {
        Test = other.Test;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Test = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class KeepAliveResponse : pb::IMessage<KeepAliveResponse> {
    private static readonly pb::MessageParser<KeepAliveResponse> _parser = new pb::MessageParser<KeepAliveResponse>(() => new KeepAliveResponse());
    public static pb::MessageParser<KeepAliveResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ipc.IpcReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public KeepAliveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public KeepAliveResponse(KeepAliveResponse other) : this() {
      test_ = other.test_;
    }

    public KeepAliveResponse Clone() {
      return new KeepAliveResponse(this);
    }

    /// <summary>Field number for the "test" field.</summary>
    public const int TestFieldNumber = 1;
    private string test_ = "";
    public string Test {
      get { return test_; }
      set {
        test_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as KeepAliveResponse);
    }

    public bool Equals(KeepAliveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Test != other.Test) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Test.Length != 0) hash ^= Test.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Test.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Test);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Test.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Test);
      }
      return size;
    }

    public void MergeFrom(KeepAliveResponse other) {
      if (other == null) {
        return;
      }
      if (other.Test.Length != 0) {
        Test = other.Test;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Test = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
